"""Type interface for :mod:`numpy_ai`.

This stub declares the public API of ``numpy_ai.py``
this file is intended for IDE completion, static type checking, API review,
and framework-level design documentation.
"""

from __future__ import annotations
import os
from abc import ABC, abstractmethod
from collections import OrderedDict
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator, Literal, Mapping, Sequence, TypeAlias

import numpy as np

__version__: str
__all__: list[str]

ArrayLike: TypeAlias = Any
ShapeLike: TypeAlias = int | Sequence[int]
AxisLike: TypeAlias = int | tuple[int, ...] | None
Reduction: TypeAlias = Literal["none", "mean", "sum"]

class NumPyAIError(Exception): ...
class ShapeError(NumPyAIError, ValueError): ...
class NumericalError(NumPyAIError, FloatingPointError): ...
class StateDictError(NumPyAIError, ValueError): ...

@dataclass(frozen=True, slots=True)
class RuntimeConfig:
    default_dtype: np.dtype[Any] = ...
    check_finite: bool = False
    eps: float = 1e-7

def get_config() -> RuntimeConfig: ...
@contextmanager
def config_context(
    *,
    default_dtype: Any | None = None,
    check_finite: bool | None = None,
    eps: float | None = None,
) -> Iterator[RuntimeConfig]: ...
def set_seed(seed: int | None) -> np.random.Generator: ...
def get_rng() -> np.random.Generator: ...
def tensor(
    data: ArrayLike, *, dtype: Any | None = None, copy: bool | None = None
) -> np.ndarray: ...
def zeros(shape: ShapeLike, *, dtype: Any | None = None) -> np.ndarray: ...
def ones(shape: ShapeLike, *, dtype: Any | None = None) -> np.ndarray: ...
def full(
    shape: ShapeLike, fill_value: Any, *, dtype: Any | None = None
) -> np.ndarray: ...
def arange(*args: Any, dtype: Any | None = None) -> np.ndarray: ...
def linspace(
    start: float,
    stop: float,
    num: int = 50,
    *,
    endpoint: bool = True,
    dtype: Any | None = None,
) -> np.ndarray: ...
def rand(
    shape: ShapeLike,
    *,
    dtype: Any | None = None,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
def randn(
    shape: ShapeLike,
    *,
    mean: float = 0.0,
    std: float = 1.0,
    dtype: Any | None = None,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
def randint(
    low: int,
    high: int | None = None,
    *,
    shape: ShapeLike = (),
    dtype: Any = np.int64,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
def one_hot(
    indices: ArrayLike, num_classes: int, *, dtype: Any | None = None
) -> np.ndarray: ...
def ensure_finite(value: ArrayLike, *, name: str = "value") -> np.ndarray: ...
def reshape(value: ArrayLike, shape: ShapeLike) -> np.ndarray: ...
def flatten(
    value: ArrayLike, *, start_dim: int = 0, end_dim: int = -1
) -> np.ndarray: ...
def transpose(value: ArrayLike, axes: Sequence[int] | None = None) -> np.ndarray: ...
def permute(value: ArrayLike, *axes: int) -> np.ndarray: ...
def squeeze(value: ArrayLike, axis: AxisLike = None) -> np.ndarray: ...
def unsqueeze(value: ArrayLike, axis: int) -> np.ndarray: ...
def concatenate(values: Sequence[ArrayLike], *, axis: int = 0) -> np.ndarray: ...
def stack(values: Sequence[ArrayLike], *, axis: int = 0) -> np.ndarray: ...
def split(
    value: ArrayLike, indices_or_sections: int | Sequence[int], *, axis: int = 0
) -> list[np.ndarray]: ...
def pad(
    value: ArrayLike,
    pad_width: Any,
    *,
    mode: str = "constant",
    constant_values: Any = 0,
) -> np.ndarray: ...
def where(condition: ArrayLike, x: ArrayLike, y: ArrayLike) -> np.ndarray: ...
def clip(
    value: ArrayLike, minimum: float | None = None, maximum: float | None = None
) -> np.ndarray: ...
def matmul(left: ArrayLike, right: ArrayLike) -> np.ndarray: ...
def einsum(
    expression: str, *operands: ArrayLike, optimize: bool = True
) -> np.ndarray: ...
def reduce_sum(
    value: ArrayLike,
    *,
    axis: AxisLike = None,
    keepdims: bool = False,
    dtype: Any | None = None,
) -> np.ndarray: ...
def reduce_mean(
    value: ArrayLike,
    *,
    axis: AxisLike = None,
    keepdims: bool = False,
    dtype: Any | None = None,
) -> np.ndarray: ...
def reduce_var(
    value: ArrayLike, *, axis: AxisLike = None, keepdims: bool = False, ddof: int = 0
) -> np.ndarray: ...
def reduce_std(
    value: ArrayLike, *, axis: AxisLike = None, keepdims: bool = False, ddof: int = 0
) -> np.ndarray: ...
def reduce_max(
    value: ArrayLike, *, axis: AxisLike = None, keepdims: bool = False
) -> np.ndarray: ...
def reduce_min(
    value: ArrayLike, *, axis: AxisLike = None, keepdims: bool = False
) -> np.ndarray: ...
def argmax(value: ArrayLike, *, axis: int | None = None) -> np.ndarray: ...
def argmin(value: ArrayLike, *, axis: int | None = None) -> np.ndarray: ...
def l2_norm(
    value: ArrayLike, *, axis: AxisLike = None, keepdims: bool = False
) -> np.ndarray: ...
def determinant(value: ArrayLike) -> np.ndarray: ...
def inverse(value: ArrayLike) -> np.ndarray: ...
def solve(coefficients: ArrayLike, right_hand_side: ArrayLike) -> np.ndarray: ...
def svd(
    value: ArrayLike, *, full_matrices: bool = False, compute_uv: bool = True
) -> Any: ...
def qr(value: ArrayLike, *, mode: str = "reduced") -> Any: ...
def normalize(
    value: ArrayLike, *, axis: AxisLike = -1, eps: float | None = None
) -> np.ndarray: ...
def cosine_similarity(
    x: ArrayLike, y: ArrayLike, *, axis: int = -1, eps: float | None = None
) -> np.ndarray: ...
def pairwise_squared_distance(x: ArrayLike, y: ArrayLike) -> np.ndarray: ...
def sigmoid(value: ArrayLike) -> np.ndarray: ...
def relu(value: ArrayLike) -> np.ndarray: ...
def leaky_relu(value: ArrayLike, negative_slope: float = 0.01) -> np.ndarray: ...
def tanh(value: ArrayLike) -> np.ndarray: ...
def softplus(value: ArrayLike, *, beta: float = 1.0) -> np.ndarray: ...
def silu(value: ArrayLike) -> np.ndarray: ...
def gelu(value: ArrayLike, *, approximate: bool = True) -> np.ndarray: ...
def softmax(value: ArrayLike, *, axis: int = -1) -> np.ndarray: ...
def log_softmax(value: ArrayLike, *, axis: int = -1) -> np.ndarray: ...
def scaled_dot_product_attention(
    query: ArrayLike,
    key: ArrayLike,
    value: ArrayLike,
    *,
    mask: ArrayLike | None = None,
    causal: bool = False,
    dropout_p: float = 0.0,
    training: bool = False,
    rng: np.random.Generator | None = None,
) -> tuple[np.ndarray, np.ndarray]: ...
def mse_loss(
    prediction: ArrayLike, target: ArrayLike, *, reduction: Reduction = "mean"
) -> np.ndarray | float: ...
def mae_loss(
    prediction: ArrayLike, target: ArrayLike, *, reduction: Reduction = "mean"
) -> np.ndarray | float: ...
def huber_loss(
    prediction: ArrayLike,
    target: ArrayLike,
    *,
    delta: float = 1.0,
    reduction: Reduction = "mean",
) -> np.ndarray | float: ...
def cross_entropy(
    logits: ArrayLike,
    targets: ArrayLike,
    *,
    reduction: Reduction = "mean",
    label_smoothing: float = 0.0,
    ignore_index: int | None = None,
) -> np.ndarray | float: ...
def binary_cross_entropy_with_logits(
    logits: ArrayLike,
    targets: ArrayLike,
    *,
    reduction: Reduction = "mean",
    pos_weight: float | None = None,
) -> np.ndarray | float: ...
def xavier_uniform(
    shape: ShapeLike,
    *,
    gain: float = 1.0,
    dtype: Any | None = None,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
def xavier_normal(
    shape: ShapeLike,
    *,
    gain: float = 1.0,
    dtype: Any | None = None,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
def kaiming_uniform(
    shape: ShapeLike,
    *,
    negative_slope: float = 0.0,
    dtype: Any | None = None,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
def kaiming_normal(
    shape: ShapeLike,
    *,
    negative_slope: float = 0.0,
    dtype: Any | None = None,
    rng: np.random.Generator | None = None,
) -> np.ndarray: ...
@dataclass(slots=True)
class Parameter:
    data: np.ndarray
    requires_grad: bool = True
    grad: np.ndarray | None = None
    def zero_grad(self) -> None: ...
    def accumulate_grad(self, gradient: ArrayLike) -> None: ...

class Module(ABC):
    training: bool
    def __init__(self) -> None: ...
    @abstractmethod
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    @abstractmethod
    def backward(self, grad_output: np.ndarray) -> np.ndarray | None: ...
    def __call__(self, x: np.ndarray) -> np.ndarray: ...
    def named_parameters(self) -> Iterator[tuple[str, Parameter]]: ...
    def parameters(self) -> list[Parameter]: ...
    def named_modules(self) -> Iterator[tuple[str, Module]]: ...
    def train(self, mode: bool = True) -> Module: ...
    def eval(self) -> Module: ...
    def zero_grad(self) -> None: ...
    def state_dict(self) -> OrderedDict[str, np.ndarray]: ...
    def load_state_dict(
        self, state: Mapping[str, ArrayLike], *, strict: bool = True
    ) -> dict[str, list[str]]: ...

class Identity(Module):
    def __init__(self) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Linear(Module):
    in_features: int
    out_features: int
    weight: Parameter
    bias: Parameter | None
    def __init__(
        self,
        in_features: int,
        out_features: int,
        *,
        bias: bool = True,
        dtype: Any | None = None,
        rng: np.random.Generator | None = None,
    ) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class ReLU(Module):
    def __init__(self) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class LeakyReLU(Module):
    negative_slope: float
    def __init__(self, negative_slope: float = 0.01) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Sigmoid(Module):
    def __init__(self) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Tanh(Module):
    def __init__(self) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class GELU(Module):
    def __init__(self) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class SiLU(Module):
    def __init__(self) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Softmax(Module):
    axis: int
    def __init__(self, axis: int = -1) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class LogSoftmax(Module):
    axis: int
    def __init__(self, axis: int = -1) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Dropout(Module):
    probability: float
    def __init__(self, probability: float = 0.5) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Flatten(Module):
    start_dim: int
    end_dim: int
    def __init__(self, start_dim: int = 1, end_dim: int = -1) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class LayerNorm(Module):
    normalized_shape: tuple[int, ...]
    eps: float
    weight: Parameter | None
    bias: Parameter | None
    def __init__(
        self,
        normalized_shape: ShapeLike,
        *,
        eps: float = 1e-05,
        elementwise_affine: bool = True,
        dtype: Any | None = None,
    ) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray: ...

class Embedding(Module):
    num_embeddings: int
    embedding_dim: int
    weight: Parameter
    def __init__(
        self,
        num_embeddings: int,
        embedding_dim: int,
        *,
        dtype: Any | None = None,
        rng: np.random.Generator | None = None,
    ) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> None: ...

class Sequential(Module):
    modules: list[Module]
    def __init__(self, *modules: Module) -> None: ...
    def forward(self, x: np.ndarray) -> np.ndarray: ...
    def backward(self, grad_output: np.ndarray) -> np.ndarray | None: ...
    def __getitem__(self, index: int) -> Module: ...
    def __len__(self) -> int: ...

class Loss(ABC):
    @abstractmethod
    def forward(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...
    @abstractmethod
    def backward(self) -> np.ndarray: ...
    def __call__(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...

class MSELoss(Loss):
    reduction: Reduction
    def __init__(self, reduction: Reduction = "mean") -> None: ...
    def forward(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...
    def backward(self) -> np.ndarray: ...

class MAELoss(Loss):
    reduction: Reduction
    def __init__(self, reduction: Reduction = "mean") -> None: ...
    def forward(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...
    def backward(self) -> np.ndarray: ...

class HuberLoss(Loss):
    delta: float
    reduction: Reduction
    def __init__(self, delta: float = 1.0, reduction: Reduction = "mean") -> None: ...
    def forward(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...
    def backward(self) -> np.ndarray: ...

class CrossEntropyLoss(Loss):
    reduction: Reduction
    label_smoothing: float
    ignore_index: int | None
    def __init__(
        self,
        *,
        reduction: Reduction = "mean",
        label_smoothing: float = 0.0,
        ignore_index: int | None = None,
    ) -> None: ...
    def forward(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...
    def backward(self) -> np.ndarray: ...

class BCEWithLogitsLoss(Loss):
    reduction: Reduction
    pos_weight: float | None
    def __init__(
        self, *, reduction: Reduction = "mean", pos_weight: float | None = None
    ) -> None: ...
    def forward(self, prediction: ArrayLike, target: ArrayLike) -> Any: ...
    def backward(self) -> np.ndarray: ...

class Optimizer(ABC):
    parameters: list[Parameter]
    lr: float
    step_count: int
    def __init__(self, parameters: Iterable[Parameter], *, lr: float) -> None: ...
    def zero_grad(self) -> None: ...
    @abstractmethod
    def step(self) -> None: ...

class SGD(Optimizer):
    momentum: float
    weight_decay: float
    dampening: float
    nesterov: bool
    def __init__(
        self,
        parameters: Iterable[Parameter],
        *,
        lr: float = 0.01,
        momentum: float = 0.0,
        weight_decay: float = 0.0,
        dampening: float = 0.0,
        nesterov: bool = False,
    ) -> None: ...
    def step(self) -> None: ...

class Adam(Optimizer):
    beta1: float
    beta2: float
    eps: float
    weight_decay: float
    amsgrad: bool
    def __init__(
        self,
        parameters: Iterable[Parameter],
        *,
        lr: float = 0.001,
        betas: tuple[float, float] = (0.9, 0.999),
        eps: float = 1e-08,
        weight_decay: float = 0.0,
        amsgrad: bool = False,
    ) -> None: ...
    def step(self) -> None: ...

class AdamW(Adam):
    def step(self) -> None: ...

def clip_grad_norm_(
    parameters: Iterable[Parameter],
    max_norm: float,
    *,
    norm_type: float = 2.0,
    error_if_nonfinite: bool = True,
) -> float: ...
def clip_grad_value_(parameters: Iterable[Parameter], clip_value: float) -> None: ...

class LRScheduler(ABC):
    optimizer: Optimizer
    base_lr: float
    last_epoch: int
    def __init__(self, optimizer: Optimizer) -> None: ...
    @abstractmethod
    def get_lr(self) -> float: ...
    def step(self) -> float: ...

class StepLR(LRScheduler):
    step_size: int
    gamma: float
    def __init__(
        self, optimizer: Optimizer, *, step_size: int, gamma: float = 0.1
    ) -> None: ...
    def get_lr(self) -> float: ...

class ExponentialLR(LRScheduler):
    gamma: float
    def __init__(self, optimizer: Optimizer, *, gamma: float) -> None: ...
    def get_lr(self) -> float: ...

class DataLoader:
    arrays: tuple[np.ndarray, ...]
    length: int
    batch_size: int
    shuffle: bool
    drop_last: bool
    def __init__(
        self,
        *arrays: ArrayLike,
        batch_size: int = 32,
        shuffle: bool = False,
        drop_last: bool = False,
        seed: int | None = None,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[np.ndarray, ...]]: ...

def accuracy_score(targets: ArrayLike, predictions: ArrayLike) -> float: ...
def confusion_matrix(
    targets: ArrayLike, predictions: ArrayLike, *, num_classes: int | None = None
) -> np.ndarray: ...
def precision_recall_f1(
    targets: ArrayLike,
    predictions: ArrayLike,
    *,
    num_classes: int | None = None,
    average: Literal["macro", "micro", "none"] = "macro",
    zero_division: float = 0.0,
) -> tuple[Any, Any, Any]: ...
def save_checkpoint(
    path: str | os.PathLike[str],
    model: Module,
    *,
    metadata: Mapping[str, Any] | None = None,
) -> Path: ...
def load_checkpoint(
    path: str | os.PathLike[str], model: Module, *, strict: bool = True
) -> dict[str, Any]: ...
def model_summary(model: Module) -> str: ...
def gradient_check(
    model: Module,
    loss: Loss,
    inputs: np.ndarray,
    targets: np.ndarray,
    *,
    epsilon: float = 0.0001,
    atol: float = 0.0001,
    rtol: float = 0.01,
    max_checks_per_parameter: int = 32,
    seed: int = 0,
) -> dict[str, Any]: ...
def train_epoch(
    model: Module,
    loader: DataLoader,
    loss_fn: Loss,
    optimizer: Optimizer,
    *,
    grad_clip_norm: float | None = None,
) -> dict[str, float]: ...
def evaluate(model: Module, loader: DataLoader, loss_fn: Loss) -> dict[str, float]: ...
